version: '3.5'

services:
  db_auth:
    container_name: mdk04-02
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
      - POSTGRES_DB=mdk04-02
    image: postgres:14.3-alpine